### ISSUE TITLE
home-page.html will not keep the page height at 100% no matter what I do

### ISSUE THREAD

**Issue by jonathanmsaylor** [jonathanmsaylor/portfolio#1]
** HOME-PAGE.HTML **

`<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Jonathan Saylor - Full-Stack Web Developer</title>

    
    <base href='/'>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
</head>

<body>
    <header>
        <nav class="navbar navbar-inverse navbar-fixed-top" style="padding: 8px; box-shadow: 5px 5px 5px rgba(4, 0, 7, 0.644); background-color: #0c0303f1;">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" style="background-image: linear-gradient(#6600ff, #ab2e8c, #c94259);" class="navbar-toggle collapsed"
                        (click)="toggleState()">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" routerLink="/" style="margin-top: 20px; color: rgb(211, 164, 104); font-family: bauhaus;">
                        <div class="name">Jonathan Saylor</div>
                    </a>
                </div>
                <a class="navbar-brand" style="font-size: 24px; font-family: bauhaus;  color: rgb(180, 73, 23); cursor: default;">
                    <div class="title">Full-Stack Web-Developer</div>
                </a>
                <div class="links">
                    <div class="collapse navbar-collapse" style="width: 105%; padding-left: 140px;" [ngClass]="{ 'in': isIn }">
                        <ul class="nav navbar-nav">
                            <li>
                                <a routerLink="/projects" style="text-align: center; letter-spacing: 2px; margin-top: 18px; padding: 13px; margin-right: 100px; color: rgb(255, 255, 255); border-radius: 5px; background-color: rgba(255, 255, 255, 0.13); border: 1px solid rgba(255, 255, 255, 0.726);">Projects</a>
                            </li>
                            <li>
                                <a routerLink="/skills" style="text-align: center; letter-spacing: 2px; margin-top: 18px; padding: 13px; margin-right: 100px; color: rgb(255, 255, 255); border-radius: 5px; background-color: rgba(255, 255, 255, 0.13); border: 1px solid rgba(255, 255, 255, 0.726);">Skills</a>
                            </li>
                            <li>
                                <a routerLink="/resume" style="text-align: center; letter-spacing: 2px; margin-top: 18px; padding: 13px; margin-right: 100px; color: rgb(255, 255, 255); border-radius: 5px; background-color: rgba(255, 255, 255, 0.13); border: 1px solid rgba(255, 255, 255, 0.726);">Resume</a>
                            </li>
                            <li>
                                <a routerLink="/art" style="text-align: center; letter-spacing: 2px; margin-top: 18px; padding: 13px; margin-right: 100px; color: rgb(255, 255, 255); border-radius: 5px; background-color: rgba(255, 255, 255, 0.13); border: 1px solid rgba(255, 255, 255, 0.726);">Art</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <div class="row" style="margin-bottom: 100px; color: rgb(230, 228, 228); border: 2px solid black; background-image: linear-gradient(#6600fff3, #ab2e8cf6, #c94258ef); padding: 20px; box-shadow: 3px 3px 3px black; border-radius: 30px;">
            <div class="col-sm">
                <p style="font-family: bauhus; font-size: 30px; text-align: center; cursor: default;">
                    <div class="homebox">
                        I am a full stack web developer that specializes in front-end technologies. I am proficient in Python, MEAN, and web fundamentals
                        stack. In addition to web development, I am an abstract artist and I use my robust imagination to
                        bring forth unique, dynamic, yet structured projects for my clients. I have a diligent work ethic
                        and I aim to bring my creativeness and experience to game development companies and front-end web
                        design projects.
                    </div>
            </div>
        </div>
    </div>
    

    <div class="container-fluid" style="padding: 0;">
        <div class="text-center center-block" style="background-color: #0c0303f1; padding: 25px; border: 2px solid rgb(8, 8, 8);">
            <p class="txt-railway" style="font-family: bauhus; font-size: 27px; color: rgb(202, 180, 151); letter-spacing: 3px; cursor: default;">- Get In Touch -</p>
            <hr>
            <a href="mailto:jsaylor23@hotmail.com" style="margin: 20px;">
                <i id="social-em" class="fa fa-envelope-square fa-3x social"></i>
            </a>
            <a href="https://github.com/jonathanmsaylor" style="margin: 20px;">
                <i id="social-git" class="fa fa-github fa-3x social"></i>
            </a>
            <a href="https://www.linkedin.com/in/jonathan-saylor/" style="margin: 20px;">
                <i id="social-linkedin" class="fa fa-linkedin fa-3x social"></i>
            </a>
        </div>
    </div>
</body>

</html>`

** HOME-PAGE.CSS**

html {
  background-image: url("https://i.ibb.co/DQSYpHK/IMG-2325.png");
  margin-bottom: 0;
  height: 100%;
}
body {
  padding-top: 150px;
  background-color: rgba(199, 177, 131, 0);
  margin-bottom: 0;
  height: 100%;
}

** STYLES.CSS **

html, body {
  width: 100%;
  margin: 0px;
  padding: 0px;
  overflow-x: hidden; 
  background-color: rgba(199, 177, 131, 0.527);
}
.social:hover {
  -webkit-transform: scale(1.6);
  -moz-transform: scale(1.6);
  -o-transform: scale(1.6);
}
.social {
  -webkit-transform: scale(1.2);
  /* Browser Variations: */
  
  -moz-transform: scale(1.2);
  -o-transform: scale(1.2);
  -webkit-transition-duration: 0.5s;
  -moz-transition-duration: 0.5s;
  -o-transition-duration: 0.5s;
}

/*
 Multicoloured Hover Variations
*/
#social-git:hover {
  color: rgb(2, 6, 15);
}
#social-em:hover {
  color: #f39c12;
}
#social-linkedin:hover {
  color: #2d4ddf;
}
.links {
    font-size: 30px;
    float: right;
    padding: 15px;
    font-family: bauhaus;
  }
  /* * { border: 1px solid red} */

  .artburntorange {
    padding: .5%;
    text-align: center;
  }

/* Custom, iPhone Retina */ 
@media only screen and (min-width : 320px) {
    .container {
      width: 95%;
      height: 55%;
    }
    .homebox {
      font-size: 19px;
      padding: 3px;
      text-align: center;
      font-family: bauhus;
    }
    .col-xs-8 {
      overflow: hidden;
      width: 200%;
    }
    .name {
      font-size: 40px;
    }
    .contactme {
      font-size: 18px;
      font-family: bauhus;
      font-size: 27px; 
      color: rgb(202, 180, 151); 
      letter-spacing: 3px; 
      cursor: default;
    }
    .social {
      -webkit-transform: scale(.9);
      /* Browser Variations: */
      -moz-transform: scale(.9);
      -o-transform: scale(.9);
      -webkit-transition-duration: 0.5s;
      -moz-transition-duration: 0.5s;
      -o-transition-duration: 0.5s;
    }
}
/* Extra Small Devices, Phones */ 
@media only screen and (min-width : 480px) {
    .container {
        width: 100%;
        height: 50%;
        padding-top: 150px;
        margin-top: 40px;
    }
    .name {
      font-size: 48px;
    }
    .footer {
      margin-top: 20px;
    }
}
/* Small Devices, Tablets */
@media only screen and (min-width : 768px) {
    .container {
        width: 100%;
        height: 100%;
    }
    .title {
      margin-left: 20px;
      margin-top: 28px;
    }
    .skillheader {
      font-size: 40px;
    }
    .footer {
      margin-top: 95.5px;
    }
}
/* Medium Devices, Desktops */
@media only screen and (min-width : 992px) {
    .container {
        width: 100%;
        height: 100%;
        margin-bottom: 80px;
    }
    .footer {
      margin-top: 95.5px;
    }
}
/* Large Devices, Wide Screens */
@media only screen and (min-width : 1200px) {
    .container {
        width: 200%;
        height: 100%;
        margin-bottom: 160px;
    }
    .footer {
      margin-top: 95.5px;
    }

}

@media screen and (max-width: 600px) {
  .burntorange {
    margin-top: 300px;
  }
  .footer {
    margin-top: 95.5px;
  }
}

**Comment by NikithaNadig** [comment]
Can I work on this? Can  you assign this to me

**Comment by jonathanmsaylor** [comment]
@NikithaNadig Yes I can! How do I do that?

**Comment by NikithaNadig** [comment]
Where is your .html file in your repository so that I can fork and work on it

**Comment by NikithaNadig** [comment]
Okay I'll get back with this.
